export function narrativeToMarkdownFile(narrative: string, title?: string): string {
  const heading = title ? `# ${title}` : "# ComputeBrief Workload Brief";
  const generatedAt = new Date().toISOString();
  return `${heading}\n\n<!-- Generated by ComputeBrief on ${generatedAt} -->\n\n${narrative}\n`;
}
